export const categoriesList = [
  { id: 1, name: 'Science', image: require('./assets/categories/science.png') },
  { id: 2, name: 'Nature', image: require('./assets/categories/nature.png') },
  { id: 3, name: 'Space', image: require('./assets/categories/space.png') },
  { id: 4, name: 'Animals', image: require('./assets/categories/animal.png') },
  { id: 5, name: 'Kindness', image: require('./assets/categories/default.png') },
  { id: 6, name: 'Art', image: require('./assets/categories/default.png') },
  { id: 7, name: 'Health', image: require('./assets/categories/default.png') },
  { id: 8, name: 'Environment', image: require('./assets/categories/default.png') },
  { id: 9, name: 'Archaeology', image: require('./assets/categories/default.png') },
  { id: 10, name: 'Dinosaurs', image: require('./assets/categories/default.png') },
  { id: 11, name: 'History', image: require('./assets/categories/default.png') },
  { id: 12, name: 'Discovery', image: require('./assets/categories/default.png') },
  { id: 13, name: 'Heartwarming', image: require('./assets/categories/default.png') },
  { id: 14, name: 'Inspiring', image: require('./assets/categories/default.png') },
  { id: 15, name: 'Friendship', image: require('./assets/categories/default.png') },
  { id: 16, name: 'Community', image: require('./assets/categories/default.png') },
  { id: 17, name: 'Charity', image: require('./assets/categories/default.png') },
  { id: 18, name: 'Sustainability', image: require('./assets/categories/default.png') },
  { id: 19, name: 'Social Progress', image: require('./assets/categories/default.png') },
  { id: 20, name: 'Sports', image: require('./assets/categories/default.png') },
  { id: 21, name: 'Technology', image: require('./assets/categories/default.png') },
  { id: 22, name: 'Education', image: require('./assets/categories/default.png') },
  { id: 23, name: 'Fashion', image: require('./assets/categories/default.png') },
  { id: 24, name: 'Music', image: require('./assets/categories/default.png') },
  { id: 25, name: 'Love', image: require('./assets/categories/default.png') },
];
export const sourcesList = [
  { id: 1, name: 'Good News Network', image: require('./assets/categories/science.png') },
  { id: 2, name: 'Yes Magazine', image: require('./assets/categories/nature.png') },
  { id: 3, name: 'Positive News', image: require('./assets/categories/space.png') },
  { id: 4, name: 'Optimist Daily', image: require('./assets/categories/animal.png') },
  { id: 5, name: 'The Bright Side', image: require('./assets/categories/default.png') },
  { id: 6, name: 'Uplifting Times', image: require('./assets/categories/default.png') },
  { id: 7, name: 'Happy Headlines', image: require('./assets/categories/default.png') },
  { id: 8, name: 'Daily Uplift', image: require('./assets/categories/default.png') },
  { id: 9, name: 'The Good Report', image: require('./assets/categories/default.png') },
  { id: 10, name: 'Hopeful Tribune', image: require('./assets/categories/default.png') },
  { id: 11, name: 'The Sunny Post', image: require('./assets/categories/default.png') },
  { id: 12, name: 'Positivity Press', image: require('./assets/categories/default.png') },
  { id: 13, name: 'Encouraging Times', image: require('./assets/categories/default.png') },
  { id: 14, name: 'The Cheerful Journal', image: require('./assets/categories/default.png') },
  { id: 15, name: 'The Kindness Chronicle', image: require('./assets/categories/default.png') },
  { id: 16, name: 'Impactful News', image: require('./assets/categories/default.png') },
  { id: 17, name: 'Hope Herald', image: require('./assets/categories/default.png') },
  { id: 18, name: 'Grateful Gazette', image: require('./assets/categories/default.png') },
  { id: 19, name: 'The Joy Report', image: require('./assets/categories/default.png') },
  { id: 20, name: 'Wellbeing Weekly', image: require('./assets/categories/default.png') },
  { id: 21, name: 'Mindful Daily', image: require('./assets/categories/default.png') },
  { id: 22, name: 'Heartwarming Herald', image: require('./assets/categories/default.png') },
  { id: 23, name: 'Acts of Kindness', image: require('./assets/categories/default.png') },
  { id: 24, name: 'Compassion Chronicle', image: require('./assets/categories/default.png') },
];
