export const categoriesList = [
  { id: 1, name: 'Animals', image: require('./assets/categories/animal.png'), emoji: '🐾' },
  {
    id: 2,
    name: 'Archaeology',
    image: require('./assets/categories/archaeology.png'),
    emoji: '🏛️',
  },
  { id: 3, name: 'Art', image: require('./assets/categories/art.png'), emoji: '🎨' },
  { id: 4, name: 'Charity', image: require('./assets/categories/charity.png'), emoji: '🤝' },
  { id: 5, name: 'Community', image: require('./assets/categories/community.png'), emoji: '👥' },
  {
    id: 6,
    name: 'Conservation',
    image: require('./assets/categories/conservation.png'),
    emoji: '🌿',
  },
  { id: 7, name: 'Culture', image: require('./assets/categories/culture.png'), emoji: '🎭' },
  { id: 8, name: 'Dinosaurs', image: require('./assets/categories/dinosaurs.png'), emoji: '🦖' },
  { id: 9, name: 'Discovery', image: require('./assets/categories/discovery.png'), emoji: '🔍' },
  { id: 10, name: 'Education', image: require('./assets/categories/education.png'), emoji: '📚' },
  {
    id: 11,
    name: 'Environment',
    image: require('./assets/categories/environment.png'),
    emoji: '🌍',
  },
  { id: 12, name: 'Fashion', image: require('./assets/categories/fashion.png'), emoji: '👗' },
  { id: 13, name: 'Food', image: require('./assets/categories/food.png'), emoji: '🍽️' },
  { id: 14, name: 'Friendship', image: require('./assets/categories/friendship.png'), emoji: '👬' },
  { id: 15, name: 'Health', image: require('./assets/categories/health.png'), emoji: '🩺' },
  {
    id: 16,
    name: 'Heartwarming',
    image: require('./assets/categories/heartwarming.png'),
    emoji: '💖',
  },
  { id: 17, name: 'History', image: require('./assets/categories/history.png'), emoji: '📜' },
  { id: 18, name: 'Indigenous', image: require('./assets/categories/indigenous.png'), emoji: '🪶' },
  { id: 19, name: 'Innovation', image: require('./assets/categories/innovation.png'), emoji: '💡' },
  { id: 20, name: 'Inspiring', image: require('./assets/categories/inspiring.png'), emoji: '✨' },
  { id: 21, name: 'Kindness', image: require('./assets/categories/kindness.png'), emoji: '😊' },
  { id: 22, name: 'Love', image: require('./assets/categories/love.png'), emoji: '❤️' },
  { id: 23, name: 'Music', image: require('./assets/categories/music.png'), emoji: '🎶' },
  { id: 24, name: 'Nature', image: require('./assets/categories/nature.png'), emoji: '🌳' },
  { id: 25, name: 'Science', image: require('./assets/categories/science.png'), emoji: '🔬' },
  {
    id: 26,
    name: 'Social Progress',
    image: require('./assets/categories/social-progress.png'),
    emoji: '🌟',
  },
  { id: 27, name: 'Space', image: require('./assets/categories/space.png'), emoji: '🚀' },
  { id: 28, name: 'Sports', image: require('./assets/categories/sports.png'), emoji: '⚽' },
  {
    id: 29,
    name: 'Sustainability',
    image: require('./assets/categories/sustainability.png'),
    emoji: '♻️',
  },
  { id: 30, name: 'Technology', image: require('./assets/categories/technology.png'), emoji: '💻' },
  { id: 31, name: 'Travel', image: require('./assets/categories/travel.png'), emoji: '✈️' },
];
export const sourcesList = [
  { id: 1, name: 'Archaeology Mag', image: require('./assets/sources/archaeology-magazine.png') },
  { id: 2, name: 'NASA', image: require('./assets/sources/nasa.png') },
  { id: 3, name: 'NPR Music', image: require('./assets/sources/npr.png') },
  { id: 4, name: 'NYTimes Arts/Design', image: require('./assets/sources/nyt.png') },
  { id: 5, name: 'NYTimes Personal Tech', image: require('./assets/sources/nyt.png') },
  { id: 6, name: 'NYTimes Science', image: require('./assets/sources/nyt.png') },
  { id: 7, name: 'NYTimes Space', image: require('./assets/sources/nyt.png') },
  { id: 8, name: 'NYTimes Tech', image: require('./assets/sources/nyt.png') },
  { id: 9, name: 'NYTimes Weddings', image: require('./assets/sources/nyt.png') },
  { id: 10, name: 'Scientific American', image: require('./assets/sources/sci-am.png') },
  { id: 11, name: 'WSJ Lifestyle', image: require('./assets/sources/wsj.png') },
  { id: 12, name: 'good good good', image: require('./assets/sources/ggg.png') },
  { id: 13, name: 'good news network', image: require('./assets/sources/goodnews-net.png') },
  { id: 14, name: 'optimist daily', image: require('./assets/sources/optimist-daily.png') },
  { id: 15, name: 'positive news', image: require('./assets/sources/pos-news.png') },
  { id: 16, name: 'reasons to be cheerful', image: require('./assets/sources/rtbc.png') },
  { id: 17, name: 'yes magazine', image: require('./assets/sources/yes-mag.png') },
];
