export const categoriesList = [
  { id: 1, name: 'Animals', image: require('../assets/categories/animal.png') },
  { id: 2, name: 'Archaeology', image: require('../assets/categories/default.png') },
  { id: 3, name: 'Art', image: require('../assets/categories/default.png') },
  { id: 4, name: 'Charity', image: require('../assets/categories/default.png') },
  { id: 5, name: 'Community', image: require('../assets/categories/default.png') },
  { id: 6, name: 'Conservation', image: require('../assets/categories/default.png') },
  { id: 7, name: 'Culture', image: require('../assets/categories/default.png') },
  { id: 8, name: 'Dinosaurs', image: require('../assets/categories/default.png') },
  { id: 9, name: 'Discovery', image: require('../assets/categories/default.png') },
  { id: 10, name: 'Education', image: require('../assets/categories/default.png') },
  { id: 11, name: 'Environment', image: require('../assets/categories/default.png') },
  { id: 12, name: 'Fashion', image: require('../assets/categories/default.png') },
  { id: 13, name: 'Food', image: require('../assets/categories/default.png') },
  { id: 14, name: 'Friendship', image: require('../assets/categories/default.png') },
  { id: 15, name: 'Health', image: require('../assets/categories/default.png') },
  { id: 16, name: 'Heartwarming', image: require('../assets/categories/default.png') },
  { id: 17, name: 'History', image: require('../assets/categories/default.png') },
  { id: 18, name: 'Indigenous', image: require('../assets/categories/default.png') },
  { id: 19, name: 'Innovation', image: require('../assets/categories/default.png') },
  { id: 20, name: 'Inspiring', image: require('../assets/categories/default.png') },
  { id: 21, name: 'Kindness', image: require('../assets/categories/default.png') },
  { id: 22, name: 'Love', image: require('../assets/categories/default.png') },
  { id: 23, name: 'Music', image: require('../assets/categories/default.png') },
  { id: 24, name: 'Nature', image: require('../assets/categories/nature.png') },
  { id: 25, name: 'Science', image: require('../assets/categories/science.png') },
  { id: 26, name: 'Social Progress', image: require('../assets/categories/default.png') },
  { id: 27, name: 'Space', image: require('../assets/categories/space.png') },
  { id: 28, name: 'Sports', image: require('../assets/categories/default.png') },
  { id: 29, name: 'Sustainability', image: require('../assets/categories/default.png') },
  { id: 30, name: 'Technology', image: require('../assets/categories/default.png') },
  { id: 31, name: 'Travel', image: require('../assets/categories/default.png') },
];
export const sourcesList = [
  { id: 1, name: 'Good News Network', image: require('../assets/categories/science.png') },
  { id: 2, name: 'Positive News', image: require('../assets/categories/space.png') },
  { id: 3, name: 'Reasons to be Cheerful', image: require('../assets/categories/default.png') },
  { id: 4, name: 'Yes Magazine', image: require('../assets/categories/nature.png') },
  { id: 5, name: 'NYTimes Science', image: require('../assets/categories/default.png') },
  { id: 6, name: 'WSJ Lifestyle', image: require('../assets/categories/default.png') },
  { id: 7, name: 'NYTimes Tech', image: require('../assets/categories/default.png') },
  { id: 8, name: 'NYTimes Personal Tech', image: require('../assets/categories/default.png') },
  { id: 9, name: 'NYTimes Space', image: require('../assets/categories/default.png') },
  { id: 10, name: 'NYTimes Weddings', image: require('../assets/categories/default.png') },
  { id: 11, name: 'NYTimes Arts/Design', image: require('../assets/categories/default.png') },
  { id: 12, name: 'Scientific American', image: require('../assets/categories/default.png') },
  { id: 13, name: 'Archaeology Mag', image: require('../assets/categories/default.png') },
  { id: 14, name: 'NPR Music', image: require('../assets/categories/default.png') },
  { id: 15, name: 'NASA', image: require('../assets/categories/default.png') },
  { id: 16, name: 'Optimist Daily', image: require('../assets/categories/animal.png') },
  { id: 17, name: 'GoodGoodGood', image: require('../assets/categories/default.png') },
];
